name: "starter"
version: "1.0.0"
usage: "Fetch,List,and Delete helm starters from github."
description: |-
  This plugin fetches, lists, and deletes helm starters from github.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/starter.sh"